version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smart_temp_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_temp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
